version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "cd ~/circleci-test"
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "ls"
      - run:
          name: "Git pull"
          command: ssh -oStrictHostKeyChecking=no -v $USER@$IP "cd ~/circleci-test git pull origin main"
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "ls"
      - run:
          name: Install
          command: ssh -oStrictHostKeyChecking=no -v $USER@$IP "npm install"
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "export PATH=~/.npm-global/bin:$PATH"
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "~/.profile"
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "pm2 pm2 restart app"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main

