version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: node:current
    steps:
      - checkout
      - run:
          name: npm-update
          command: 'npm install -g npm@latest'
      - run:
          name: pull
          command: 'git config --list'
      - run: 'npm -v'
      - run: 'npm install -g pm2'
      - run: 'pm2 -v'
      - run: 'git pull'
      - run: 'npm i'
      - run: pm2 start app.js --name "app"
      - run: docker ps
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy.sh"
      

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main

